# Generated by Django 4.1.5 on 2023-01-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marca', models.CharField(max_length=50)),
                ('estoque', models.BooleanField(default=False)),
            ],
        ),
    ]
